javascript kadai2 after
madoka-glass/b-teck pull request #1
Opened 2020-07-14 07:49 UTC by madoka-glass

2020-07-14 11:34 UTC, myzktkyk requested changes
何点か指摘をしておりますのでご確認ください。
全体的な指摘としてはコードのフォーマット（整形）がされていない部分が散見されます。
最近のエディターですとショートカットで瞬時にフォーマットできますので
コード記述時の習慣としてほしいです。

2020-07-14 11:34 UTC, myzktkyk commented on kadai2.html
> +		if(fizz_invalid || buzz_invalid){
このチェック内容ですと小数が入力された場合エラーにできません。
チェック内容を見直してみてください。

2020-07-14 11:34 UTC, myzktkyk commented on kadai2.html
> +	var defaultHTML;
昨今の javascript のお作法として `var` は使わない場合はほとんどです。
再代入を行う場合は `let` 一度代入したら変更しないものについては `const` を使うようにしてください。

2020-07-15 02:10 UTC, madoka-glass commented on kadai2.html
> +		if(fizz_invalid || buzz_invalid){
入力値を数値に変換する際に小数部を切り落としていたために問題が発生しておりました。
parseIntからparseFloatに修正しております。

2020-07-15 02:11 UTC, madoka-glass commented on kadai2.html
> +	var defaultHTML;
ありがとうございます、承知いたしました。

2020-07-16 12:04 UTC, kouki-iwahara commented on kadai2.html
> +    for (let i = 1;; i++) {
修正は不要ですが、条件式を記述する方が一般的です。

2020-07-17 08:51 UTC, closed without merging