JavaScript　課題3-1
madoka-glass/b-teck pull request #2
Opened 2020-07-17 08:52 UTC by madoka-glass

2020-07-17 11:50 UTC, myzktkyk requested changes
課題の要件はバッチリ満たせていていますね！

ただ…今の実装方法ですとタスク状態変更機能など
今後様々な機能を追加する際に、苦労することになります。

なので、以下のような実装方法に変更しましょう！

1. 入力されたタスク内容とその状態（デフォルトでは作業中）をオブジェクトで管理する
2. 上記のオブジェクトをはtodosという名前の配列に追加することで、複数のタスクを管理する。
3. todo配列の内容を表示させる関数（displayTodos）を定義する

オブジェクトの内容は以下のような感じになります。

```
todo = {
            task: '入力されたタスク'
            status: '作業中'
       }
```

2020-07-18 13:25 UTC, myzktkyk requested changes
全体的なリファクタリング（再構成）お疲れさまでした！
動作上は問題ないのですが、よりよくできるポイントがあったので指摘をしております。

2020-07-18 13:25 UTC, myzktkyk commented on kadai3-1.html
> +    if (table.rows.length === INITIAL_ROW_NUM) {
この部分は以下のようにすればもっと単純になるのではないでしょうか？

- `todos.push(newTodo)` をする
  - `push` を行うと配列の末尾に追加される
-  `todos.foreach` を利用して Id を `1` から振り直す

2020-07-19 06:14 UTC, madoka-glass commented on kadai3-1.html
> +    if (table.rows.length === INITIAL_ROW_NUM) {
ご確認ありがとうございます！

私の理解力不足で申し訳ないのですが、内容について確認させてください。

『`todos.foreach` を利用して Id を `1` から振り直す』の部分なのですが、

`todos.foreach`のindexを利用して、この時点（createTodos関数の中）で各配列にIDも設定するとよりよい

という認識で合っていますでしょうか。

よろしくお願い致します。

2020-07-21 23:43 UTC, shouya31 commented on kadai3-1.html
> +    if (table.rows.length === INITIAL_ROW_NUM) {
> todos.foreachのindexを利用して、この時点（createTodos関数の中）で各配列にIDも設定するとよりよい

「より良い」をもう少し具体化すると
使用することで、記述量を減らせるのでコードが見やすくなる
という点で良いです^^

2020-07-21 23:46 UTC, shouya31 commented
LGTM

2020-07-22 01:31 UTC, madoka-glass commented on kadai3-1.html
> +    if (table.rows.length === INITIAL_ROW_NUM) {
ご回答ありがとうございます！

補足ありがとうございます。
余計な変数を減らすという点でも有効ですね。
以後意識してまいります！

2020-07-22 01:36 UTC, merged