kadai3-2 after
madoka-glass/b-teck pull request #3
Opened 2020-07-22 01:43 UTC by madoka-glass

お手数ですが、レビューをお願い致します。

2020-07-22 11:55 UTC, myzktkyk requested changes
何点か指摘をしております m(_ _)m

2020-07-22 11:55 UTC, myzktkyk commented on kadai3-2.html
> +                task: table.rows[i].cells[TODO_COLUMN].innerHTML,
このあたりの処理を見ていると、すでに todo が1件以上入力されていた場合
既に画面に表示されている todo(html table の各行) を一度オブジェクトに変換する
ということをされていますが、これだと最初の指摘で申し上げた
`入力されたタスク内容とその状態（デフォルトでは作業中）をオブジェクトで管理する` ことになっていません。

期待している流れは

1. 入力値から todo オブジェクトを作り todos 配列に格納する
1. todos 配列の内容を html の table に整形してブラウザに表示

となります。

2020-07-22 11:55 UTC, myzktkyk commented on kadai3-2.html
> +        buttonDelete.setAttribute('onclick', 'deleteRow(this)');
確かにこのような形でもボタンにイベント処理を紐づけることはできますがあまり良い方法ではありません。
（例えば `deleteRow` の名前を変更したくなった時に IDE やエディタの機能を使った安全な名称変更ができない、関数/メソッドの利用箇所を調べようとしたときに調査対象から漏れる等）

以下のように `addEventListener` を利用してみてはいかがでしょうか？

```suggestion
        buttonDelete.addEventListener('click', () => {
            // deleteRow と同じ内容を記述する
        });
```

2020-07-25 07:27 UTC, kouki-iwahara commented on kadai3-2.html
> +        tr.appendChild(createStatBtn(todo));
createStatBtnでreturnされた要素は、変数を用意して一度格納しましょう。
予期せぬバグの原因になったり、可読性の低下に繋がります。
const hoge = createStatBtn(todo)

2020-07-25 08:19 UTC, madoka-glass commented on kadai3-2.html
> +        tr.appendChild(createStatBtn(todo));
ご指摘ありがとうございます！
ちなみに`createDelBtn()`で返した値はそのまま`appendChild`の引数にして問題ないのはどのような理由からなのでしょうか。

2020-07-26 12:52 UTC, Dok1211 commented on kadai3-2.html
> +    <input type="radio" name="status" 　value="all" checked>すべて
valueの前に全角スペースがあります
プログラミング全般に言えるのですが、基本的にコーディングには全角スペースは使用しないようにしましょう
（日本語の文字列でどうしても全角スペースが必要な場合以外）

2020-07-26 12:52 UTC, Dok1211 commented on kadai3-2.html
> +    <p><input type="text" id="taskname"><input type="button" id="addButton" class="button" value="追加"></input></p>
tasknameはキャメルケースにしましょう
inputタグが閉じられていないので閉じタグを入れましょう
あと特別な理由がない限りはタグごとに改行をいれてインデントを揃えましょう

2020-07-26 12:52 UTC, Dok1211 commented on kadai3-2.html
> +    todoList.forEach( todo => {
todoの前の半角スペースは不要です

2020-07-26 12:52 UTC, Dok1211 commented on kadai3-2.html
> +    <table id="tasklist">
tasklistはキャメルケースにしましょう

2020-07-26 12:52 UTC, Dok1211 commented on kadai3-2.html
> +        task: document.getElementById('taskname').value,
今の実装だとinputが空でもタスクを追加してしまうので、空の場合は追加しないようにしてみましょう
また、タスク追加時はinputを一旦空にするようにしましょう

2020-07-27 11:50 UTC, kouki-iwahara commented on kadai3-2.html
> +        tr.appendChild(createStatBtn(todo));
>ちなみにcreateDelBtn()で返した値はそのままappendChildの引数にして問題ないのはどのような理由からなのでしょうか。

createDelBtnも同じように変数に格納した方が良いです。
言葉足らず、失礼しました。。

2020-07-27 11:52 UTC, kouki-iwahara commented on kadai3-2.html
> +      task.value = "";
jsでは文字列は`''`で囲みましょう。

2020-07-28 02:27 UTC, merged